period: "2024-04"
account:
  - name: "mrhost"
    platform:
      - name: "Booking"
        parse: "API"
        # parse: API or HTML
        cookie: "px_init=0; pcm_consent=analytical%3Dtrue%26countryCode%3DTW%26consentId%3D26fe83cd-e049-4892-b004-eb991d16ea98%26consentedAt%3D2024-03-01T09%3A59%3A38.827Z%26expiresAt%3D2024-08-28T09%3A59%3A38.827Z%26implicit%3Dtrue%26marketing%3Dtrue%26regionCode%3DTPE%26regulation%3Dnone%26legacyRegulation%3Dnone; cors_js=1; bkng_sso_session=e30; bkng_sso_ses=e30; _scid=632ca933-8e39-45dc-978b-22d9f2133fc9; _gcl_au=1.1.1028764941.1709287182; FPID=FPID2.2.puV5sbDGN%2Fyp4qTmzOMQt9D%2B2gZvJiCmP4ZCa0d%2F4a0%3D.1709287181; _pxvid=71492648-d7b2-11ee-bd1a-1f8ea553a7f6; bkng_bfp=d5832ae7360eb5dc9d718b3cd860c064; ecid=Pk0Xb7LX7hGijuJH5uenSA6K; hauavc=EFB0F7D3Fv2d%2FzTUUl2uQtph8VrzzgXC7sowu4lGvC01XtC3MFWMWwmkZei%2FG%2BCUF%2FBQWoOwM; external_host=account.booking.com; uz=e; _mkto_trk=id:261-NRZ-371&token:_mch-booking.com-1709287319289-49995; extranet_cors_js=1; _sfid_2a26={%22anonymousId%22:%224913e5644948c66f%22%2C%22consents%22:[]}; _pin_unauth=dWlkPVpHUXhabVZoWmprdFl6azVNUzAwWTJZeUxXSTVPR0V0TXpWbVpEazFNVEZsWm1GaA; _evga_c2e4={%22uuid%22:%224913e5644948c66f%22%2C%22puid%22:%22etbf-Ip5qb5E0NpqcwqXtoMGckNDBmJ1NF4djum4vPgveTrDpnLopcPLcN_9KLqGyxQI7fvtSrAH93c91MDgKgsUg_BTE5Z0dVAY6qWOsUk%22%2C%22affinityId%22:%220Bu%22}; _yjsu_yjad=1711942111.a3c4eff8-17e9-4abf-9da5-fb9da3af00d2; _sctr=1%7C1711900800000; _sg_b_n=1711942186589; pcm_personalization_disabled=0; _scid_r=632ca933-8e39-45dc-978b-22d9f2133fc9; _uetvid=6c667be0d7b211eeb0eb497ae17405ce; _ga_FPD6YLJCJ7=GS1.1.1713411559.9.0.1713411572.47.0.0; _ga_A12345=GS1.1.1713411559.9.0.1713411572.0.0.123313103; _ga=GA1.2.1536445570.1709287181; _gid=GA1.2.878277207.1713840135; bkng=11UmFuZG9tSVYkc2RlIyh9YXSgTtYpR%2F1WOjMvuuinviHG%2BvD38eR%2FEkSeCqfkSOAZlbsbOOXte5ezyqQX8w0e7PlMYvUp1izUewBco3ikQXKpK7kV%2FwfCPtJrv3WcZ11OkZzUap6uuUi9FI4lbyFgXTbV3DOGS%2Bn0Njfvzn7IknIFVr7Nfv3wjLJ0uLkCUnFTvS%2FIGgVGu1cAgRDfXvR48Q%3D%3D; bkng_sso_auth=CAIQsOnuTRpmGHJfPG1T0HY/OtYUvebc5ix4lUqFaqA6AJuycZhRhRZbWuS5/jShpqOr02zkC1emdv2vQguhSv5YTzH0NsL0ENjRTFTGNaHejxKmt8bgds25kiKXiaxfA3iLRoIA9gxYfqdzgkNx; pxcts=1cbb2b8b-011b-11ef-8abd-bcb8f9ae2179; _sg_b_v=34%3B110774%3B1713840143; aws-waf-token=88f3e96f-4efe-4ce4-9474-2a4bd0562e1c:AAoAtyUR3XwLAAAA:PPwXNx6/QpJnRup2eXe8gbtvpoh0cRsI0VP3sA9K5Pa7WimsgxrgJ9Z4vrJJMdwxRF17D7HpfYrbk/q6rncYVwZn2z4yuAgSsStXz6p47Dvbne2Rw9Pfgv16sO4mYBlh/G73wnlNI2i9nVzfF+fi3WyFW+v7LCpK2i7weaBu0q4cbyDuEpoPWxNal1+wZ1bp4Q/WKoPUIW9i9ZSOFfkGO+mPru56bmPAwfOEhFacsJICd4Mv; _sg_b_p=%2Fhotel%2Fhoteladmin%2Fgroups%2Fhome%2Findex.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Fhome.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Fsearch_reservations.html; OptanonConsent=isGpcEnabled=0&datestamp=Tue+Apr+23+2024+10%3A42%3A40+GMT%2B0800+(%E5%8F%B0%E5%8C%97%E6%A8%99%E6%BA%96%E6%99%82%E9%96%93)&version=202305.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=1dfa53b2-c5e3-4927-8e7e-52dee9892c51&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0004%3A1&AwaitingReconsent=false; liteha=%5B%7B%22actions%22%3A%5B%5D%2C%22page%22%3A%22home%22%7D%2C%7B%22actions%22%3A%5B%5D%2C%22page%22%3A%22search_reservations%22%7D%5D; _px3=d166e8890594a9f1c4351320e5ae2d589b05391c3d1250c6b1fccbe2c8496d4e:+on2/VGZapyWI+OMY4xj62SYpfjwYA20zABuqeOCtmmUiICYbPSjj3PmGyEZ+ypO+FNVI3oK6SmZv7RaEcogzw==:1000:cNpvMgrCkmvKBbQ10K8xOyhBn2scCY+wdF63ePgX6/RwmO9RTmOUMF12h8X8IbVoUz90cSc0fErxjjZeTuGVn+EWF/R9hFanM9uBVzAxP/2i2djUi5gQND5K8reqXNmY+WV2xUrkcrL1F+mexEMt/hkxvvLLzRm4LY9E81MoIbhfI1CSUwNIlCsAxMf50CqLGrHIX8k4dXMdnkPwbCssVo7s/LhYS/NGSx/iaL+zmIQ=; _pxde=8fd9924600645eccb4b4a8e3be13a9083609ed175db17be2c6517fe31b707dd4:eyJ0aW1lc3RhbXAiOjE3MTM4NDAxNjE3MjAsImZfa2IiOjAsImlwY19pZCI6W119; esadm=02UmFuZG9tSVYkc2RlIyh9YbxZGyl9Y5%2BPdYDAgM9EQkI%2Flg72wnCGP2VWXfFtqO56LawRcHw8vyQ%3D; _gat=1"
        token: "X1gnZgAAAAA=uCQP-zOXod1nqdLeKJ9GOoeHFa7S4L9E6dFR1Sc5TJK7OOV5pErXVBOLzHOBQZKAQkrj0jsHfq_BiU3KdNA_FC3mX9ynHY3L3UWRx9mVpU6EYF6s5bGHeju_HMQ5lrM264iMEzbpa-eO2o0AMhTrRPTE74ozxVIXHlSTmwt4wCejF-1hER74pl1Y2y8"
        hotel:
          - name: "飛包客青年旅店"
            hotelid: "5393471"
          - name: "北門窩泊旅"
            hotelid: "1886001"
          - name: "台北西門窩青年旅館"
            hotelid: "1246970"
          - name: "府城窩旅"
            hotelid: "7570468"
          - name: "洄瀾窩青年旅舍"
            hotelid: "1461770"
          - name: "三德大飯店"
            hotelid: "337124"
          - name: "閑閑的海"
            hotelid: "10013247"
          - name: "安蘭居旅店"
            hotelid: "1957356"
          - name: "福憩背包客棧和平館"
            hotelid: "1499382"
          - name: "福憩背包客棧緣憩館"
            hotelid: "3962873"
          - name: "幸福旅行.舍"
            hotelid: "2263042"
          - name: "好宿民宿"
            hotelid: "2544838"
          - name: "欣京棧民宿"
            hotelid: "7843114"
          - name: "京棧興盛民宿"
            hotelid: "4535163"
          - name: "享棧民宿"
            hotelid: "1896315"
          - name: "CHECK inn Phnom Penh BKK1"
            hotelid: "5410294"
          - name: "CHECK inn Phnom Penh Royal Palace"
            hotelid: "10121752"
          - name: "水明漾私人villa"
            hotelid: "10915563"
          - name: "花蓮 翔廬渡假民宿"
            hotelid: "2109034"
          - name: "河沿悅舍精品民宿"
            hotelid: "1545907"
          - name: "薇薇青旅-嚞驫驛站"
            hotelid: "11050431"
          - name: "白紙寓所"
            hotelid: "4459006"
          - name: "D3經典民宿"
            hotelid: "3963347"
          - name: "河沿悅舍ZW"
            hotelid: "3638010"
          - name: "花蓮 星潮度假民宿"
            hotelid: "11256785"
          - name: "納美克星球"
            hotelid: "11381089"
          - name: "上河圖渡假會館"
            hotelid: "11149171"
          - name: "陌懷宿"
            hotelid: "6822019"
          - name: "嵐羽蒔光"
            hotelid: "11205965"
          - name: "墾丁三角涵宿"
            hotelid: "1599434"
          - name: "大衛營會館"
            hotelid: "11212354"
          - name: "月牙泉渡假行館"
            hotelid: "2868070"
          - name: "靜河畔民宿"
            hotelid: "11263647"
          - name: "壺宴楓旅店"
            hotelid: "9686161"
          - name: "漢彌敦大飯店"
            hotelid: "485559"
          - name: "巨地花園渡假莊園"
            hotelid: "6181465"
          - name: "夢樓旅店"
            hotelid: "2603582"
          - name: "承攜行旅台北大稻埕館"
            hotelid: "9222248"
          - name: "老闆的家"
            hotelid: "11420027"
          - name: "給恰旅店"
            hotelid: "4237823"
          - name: "清境31民宿"
            hotelid: "2337511"
          - name: "松悅民宿"
            hotelid: "7732566"
          - name: "萬國"
            hotelid: "11349170"
          - name: "畫水民宿"
            hotelid: "8457223"
          - name: "土造粗樓民宿"
            hotelid: "11355228"
          - name: "小海豚民宿"
            hotelid: "7725664"
          - name: "雲棧民宿"
            hotelid: "6390640"
          - name: "千尋民宿"
            hotelid: "11416717"
          - name: "北歐小宅民宿"
            hotelid: "6621669"
          - name: "空島民宿"
            hotelid: "9935857"
          - name: "槺inn"
            hotelid: "8317755"
          - name: "小舅的家包棟民宿"
            hotelid: "7108164"
          - name: "佑佑11號民宿"
            hotelid: "3065675"
          - name: "171幸福旅店"
            hotelid: "11662522"
          - name: "大湖一品苑"
            hotelid: "11622026"
          - name: "J 閣民宿"
            hotelid: "11648572"
          - name: "花漾非凡民宿"
            hotelid: "1848297"
          - name: "金洙椏民宿"
            hotelid: "836415"
          - name: "喜田小樹包棟民宿"
            hotelid: "11671697"
          - name: "菘畫居會館"
            hotelid: "2594750"
          - name: "錸捷行旅"
            hotelid: "11559442"
          - name: "GVR Genting Highlands"
            hotelid: "11277549"
          - name: "bp pool"
            hotelid: "8648936"
          - name: "尖尖民宿"
            hotelid: "4135548"
          - name: "英倫小鎮"
            hotelid: "11720823"
          - name: "阿爾卑斯莊園"
            hotelid: "1286096"
          - name: "海田行館"
            hotelid: "3290810"
          - name: "Amber Cove"
            hotelid: "10723691"
          - name: "亞馨文旅"
            hotelid: "422471"
          - name: "冬映民宿"
            hotelid: "8724181"
          - name: "3006"
            hotelid: "11336554"
          - name: "33A01"
            hotelid: "10915247"
          - name: "Luxpro Homestay"
            hotelid: "10527363"
          - name: "Pool / Sea View"
            hotelid: "10842541"
          - name: "Smart home"
            hotelid: "11336711"
