period: "2024-02"
account:
  - name: "mrhost"
    platform:
      - name: "Booking"
        parse: "HTML"
        # type: API or HTML
        cookie: "px_init=0; pcm_consent=analytical%3Dtrue%26countryCode%3DTW%26consentId%3D26fe83cd-e049-4892-b004-eb991d16ea98%26consentedAt%3D2024-03-01T09%3A59%3A38.827Z%26expiresAt%3D2024-08-28T09%3A59%3A38.827Z%26implicit%3Dtrue%26marketing%3Dtrue%26regionCode%3DTPE%26regulation%3Dnone%26legacyRegulation%3Dnone; cors_js=1; bkng_sso_session=e30; bkng_sso_ses=e30; _scid=632ca933-8e39-45dc-978b-22d9f2133fc9; _gcl_au=1.1.1028764941.1709287182; FPID=FPID2.2.puV5sbDGN%2Fyp4qTmzOMQt9D%2B2gZvJiCmP4ZCa0d%2F4a0%3D.1709287181; _pxvid=71492648-d7b2-11ee-bd1a-1f8ea553a7f6; bkng_bfp=d5832ae7360eb5dc9d718b3cd860c064; ecid=Pk0Xb7LX7hGijuJH5uenSA6K; hauavc=EFB0F7D3Fv2d%2FzTUUl2uQtph8VrzzgXC7sowu4lGvC01XtC3MFWMWwmkZei%2FG%2BCUF%2FBQWoOwM; external_host=account.booking.com; uz=e; _mkto_trk=id:261-NRZ-371&token:_mch-booking.com-1709287319289-49995; extranet_cors_js=1; _sfid_2a26={%22anonymousId%22:%224913e5644948c66f%22%2C%22consents%22:[]}; _pin_unauth=dWlkPVpHUXhabVZoWmprdFl6azVNUzAwWTJZeUxXSTVPR0V0TXpWbVpEazFNVEZsWm1GaA; _evga_c2e4={%22uuid%22:%224913e5644948c66f%22%2C%22puid%22:%22etbf-Ip5qb5E0NpqcwqXtoMGckNDBmJ1NF4djum4vPgveTrDpnLopcPLcN_9KLqGyxQI7fvtSrAH93c91MDgKgsUg_BTE5Z0dVAY6qWOsUk%22%2C%22affinityId%22:%220Bu%22}; _yjsu_yjad=1711942111.a3c4eff8-17e9-4abf-9da5-fb9da3af00d2; _sctr=1%7C1711900800000; _sg_b_n=1711942186589; pcm_personalization_disabled=0; BJS=-; FPLC=8K4P4gCQaUDTGdTEKvWCHpakYjgXtmxl%2F28txdlakvV6MDpC5AuJjT5AEEfm%2FD8emv8t4baBV4rkKUO0g6kk4tMJ0jjuAnS8mQ0SCQfOE1BG8nbJCIeBPghvv5o%2FSg%3D%3D; _gid=GA1.2.1052312340.1712137180; bkng_sso_auth=CAIQsOnuTRpmYDH0H1Zzs0qfi7UoJBjiU08cGGsrHQ+KqDvZ1ixPir34SkFPCtyX94tAhBqUFEZAo4bpJlCfK3dLbS7rXtL9DvqIu05n0KSIKG9VWxz/JVudRd1xXRe/vUxhJ596ZLlMnIGi8e63; bkng_prue=1; _scid_r=632ca933-8e39-45dc-978b-22d9f2133fc9; _uetsid=0f78ff60f19e11eebf8e5123982482f8; _uetvid=6c667be0d7b211eeb0eb497ae17405ce; _ga_FPD6YLJCJ7=GS1.1.1712200366.7.0.1712200372.54.0.0; _ga_A12345=GS1.1.1712200366.7.0.1712200372.0.0.167515309; lastSeen=1712200372836; _ga=GA1.2.1536445570.1709287181; pxcts=3b5e8630-f231-11ee-b4e2-a5fd3d0bec62; bkng=11UmFuZG9tSVYkc2RlIyh9YfDNyGw8J7nzPnUG3Pr%2Bfv5iyz1NtopREBuV41PPL9xrsR6XJjyFC9yRzzAfgGrgVXNwu7ozuO20IXGccTekL1W0lLcYvpX4zrv%2FcVn0070YtYEK8FTitr1NDLxgZ3uRO9YejfTCz%2Fvc0vHwJPS4un9%2B3RFf3QytCvqrysEEfCotxVVHZH6HhFfwnQ%2F9mUCyaw%3D%3D; aws-waf-token=22f5d5c6-625d-4c52-8799-4a3a472461ae:AAoAc7QWM0wEAAAA:Xdbb/IyxV7Uc9rzjrl9nuDJxqDd+XXAhh9IHbez/qdjl7F71v5C2H6c82Rbj+T1b7ezx+Lrb65Fj/484wcYgysIH5rdln13yDwTn9EifK9M/InUU3aTDB19evrbn4LOEMJBpXcT0FXU7xcoKWgiDtLHrkOTZ1Z5st4GYMAwq5hOSkwspf+fa9uvPM16co540vyN9rqeL0P01gfcRCh5M3zrexXP7PpH8/iH0hzDcNLICEqMi; liteha=%5B%7B%22actions%22%3A%5B%5D%2C%22page%22%3A%22finance_reservations%22%7D%2C%7B%22actions%22%3A%5B%5D%2C%22page%22%3A%22finance_reservations%22%7D%2C%7B%22actions%22%3A%5B%5D%2C%22page%22%3A%22finance_reservations%22%7D%5D; _sg_b_p=%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Fhome.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Fhome.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html%2C%2Fhotel%2Fhoteladmin%2Fextranet_ng%2Fmanage%2Ffinance_reservations.html; OptanonConsent=isGpcEnabled=0&datestamp=Thu+Apr+04+2024+11%3A24%3A59+GMT%2B0800+(%E5%8F%B0%E5%8C%97%E6%A8%99%E6%BA%96%E6%99%82%E9%96%93)&version=202305.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=1dfa53b2-c5e3-4927-8e7e-52dee9892c51&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0004%3A1&AwaitingReconsent=false; esadm=02UmFuZG9tSVYkc2RlIyh9YbxZGyl9Y5%2BP5QQEEVJThU0yaAH7LYTCYYnkaPFelWnYeTcXm0k6zng%3D; _px3=3ff1316b22b66dad198e5bc0a0af57136dc7493d93916766815b8f0dbbe26dc4:REq3gfr/puPcFSkPfFYRP2gPcdURjIiVsByd8OEW2K8PxpiKyC7wIlOdP4N9FVQvMp1IWDZIlb+RjBs9KNPkbQ==:1000:0oqTEzbffQ4LMOQsGLPyETFetT5aW4x1iSigIlivUqkM2ze01s/16NuXMuZNQT82Q/+pjsqQOrLt80mfg1DIH7fn4tCDUvR2A8H+GTo+AqwMmB6DWQqcnktzqUjcl+aGj+fr5Qj0ZYNW5UMM0ZnEVICfkhLeR0FtPL3uxdAeGPLYS6B9vDA3X3KlFmNbO2ubWoqL3pwxuuwTPMiHe2GZBzdlrbuLtlN2I8sQHc5ZxWY=; _pxde=e784a9ad4b2f943c83757162797e1b8b4531101575646d5b28fddb7a205b85fc:eyJ0aW1lc3RhbXAiOjE3MTIyMDIwODY4MTksImZfa2IiOjAsImlwY19pZCI6W119; _sg_b_v=26%3B65518%3B1712200382"
        token: "AKQLZgAAAAA=I5mVYg-2pCk7GChDtSzD_P6tOEn24Zn0HCB8SCQnZ28osds35FzcZZvKPVaFR8FBBOza-HxdcNET4makaG-EmE14u-fVYHx6gKGDhUgA7KlwDZqB_byFFRolYB1mOQV2NTD6w7acuoXnl5ULGYSwcQr5anNfRtfd0Xx67H59zqK8OSyQrwJUiRAhnPg"
        hotel:
          # - name: "飛包客青年旅店"
          #   hotelid: "5393471"
          # - name: "北門窩泊旅"
          #   hotelid: "1886001"
          - name: "台北西門窩青年旅館"
            hotelid: "1246970"
          # - name: "府城窩旅"
          #   hotelid: "7570468"
          # - name: "洄瀾窩青年旅舍"
          #   hotelid: "1461770"
          # - name: "三德大飯店"
          #   hotelid: "337124"
          # - name: "閑閑的海"
          #   hotelid: "10013247"
          # - name: "安蘭居旅店"
          #   hotelid: "1957356"
          # - name: "福憩背包客棧和平館"
          #   hotelid: "1499382"
          # - name: "福憩背包客棧緣憩館"
          #   hotelid: "3962873"
          # - name: "幸福旅行.舍"
          #   hotelid: "2263042"
          # - name: "好宿民宿"
          #   hotelid: "2544838"
          # - name: "欣京棧民宿"
          #   hotelid: "7843114"
          # - name: "京棧興盛民宿"
          #   hotelid: "4535163"
          # - name: "享棧民宿"
          #   hotelid: "1896315"
          # - name: "CHECK inn Phnom Penh BKK1"
          #   hotelid: "5410294"
          # - name: "CHECK inn Phnom Penh Royal Palace"
          #   hotelid: "10121752"
          # - name: "水明漾私人villa"
          #   hotelid: "10915563"
          # - name: "花蓮 翔廬渡假民宿"
          #   hotelid: "2109034"
          # - name: "河沿悅舍精品民宿"
          #   hotelid: "1545907"
          # - name: "薇薇青旅-嚞驫驛站"
          #   hotelid: "11050431"
          # - name: "白紙寓所"
          #   hotelid: "4459006"
          # - name: "D3經典民宿"
          #   hotelid: "3963347"
          # - name: "河沿悅舍ZW"
          #   hotelid: "3638010"
          # - name: "花蓮 星潮度假民宿"
          #   hotelid: "11256785"
          # - name: "納美克星球"
          #   hotelid: "11381089"
          # - name: "上河圖渡假會館"
          #   hotelid: "11149171"
          # - name: "陌懷宿"
          #   hotelid: "6822019"
          # - name: "嵐羽蒔光"
          #   hotelid: "11205965"
          # - name: "墾丁三角涵宿"
          #   hotelid: "1599434"
          # - name: "大衛營會館"
          #   hotelid: "11212354"
          # - name: "月牙泉渡假行館"
          #   hotelid: "2868070"
          # - name: "靜河畔民宿"
          #   hotelid: "11263647"
          # - name: "壺宴楓旅店"
          #   hotelid: "9686161"
          # - name: "漢彌敦大飯店"
          #   hotelid: "485559"
          # - name: "巨地花園渡假莊園"
          #   hotelid: "6181465"
          # - name: "夢樓旅店"
          #   hotelid: "2603582"
          # - name: "承攜行旅台北大稻埕館"
          #   hotelid: "9222248"
          # - name: "老闆的家"
          #   hotelid: "11420027"
          # - name: "給恰旅店"
          #   hotelid: "4237823"
          # - name: "清境31民宿"
          #   hotelid: "2337511"
          # - name: "松悅民宿"
          #   hotelid: "7732566"
          # - name: "萬國"
          #   hotelid: "11349170"
          # - name: "畫水民宿"
          #   hotelid: "8457223"
          # - name: "土造粗樓民宿"
          #   hotelid: "11355228"
          # - name: "小海豚民宿"
          #   hotelid: "7725664"
          # - name: "雲棧民宿"
          #   hotelid: "6390640"
          # - name: "千尋民宿"
          #   hotelid: "11416717"
          # - name: "北歐小宅民宿"
          #   hotelid: "6621669"
          # - name: "空島民宿"
          #   hotelid: "9935857"
          # - name: "槺inn"
          #   hotelid: "8317755"
          # - name: "小舅的家包棟民宿"
          #   hotelid: "7108164"
          # - name: "佑佑11號民宿"
          #   hotelid: "3065675"
          # - name: "171幸福旅店"
          #   hotelid: "11662522"
          # - name: "大湖一品苑"
          #   hotelid: "11622026"
          # - name: "J 閣民宿"
          #   hotelid: "11648572"
          # - name: "花漾非凡民宿"
          #   hotelid: "1848297"
          # - name: "金洙椏民宿"
          #   hotelid: "836415"
          # - name: "喜田小樹包棟民宿"
          #   hotelid: "11671697"
          # - name: "菘畫居會館"
          #   hotelid: "2594750"
          # - name: "錸捷行旅"
          #   hotelid: "11559442"
          # - name: "GVR Genting Highlands"
          #   hotelid: "11277549"
          # - name: "bp pool"
          #   hotelid: "8648936"
          # - name: "尖尖民宿"
          #   hotelid: "4135548"
          # - name: "英倫小鎮"
          #   hotelid: "11720823"
          # - name: "阿爾卑斯莊園"
          #   hotelid: "1286096"
          # - name: "海田行館"
          #   hotelid: "3290810"
          # - name: "Amber Cove"
          #   hotelid: "10723691"
          # - name: "亞馨文旅"
          #   hotelid: "422471"
          # - name: "冬映民宿"
          #   hotelid: "8724181"
          # - name: "3006"
          #   hotelid: "11336554"
          # - name: "33A01"
          #   hotelid: "10915247"
          # - name: "Luxpro Homestay"
          #   hotelid: "10527363"
          # - name: "Pool / Sea View"
          #   hotelid: "10842541"
          # - name: "Smart home"
          #   hotelid: "11336711"
