period: "2024-06"
account:
  - name: "mrhost"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; OrderCount=9; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1719802347&Expires=1720407146757; imislogin=9597315^1; librauuid=; randomkey=46ff078c-80ed-4fa3-8805-a383275e95af; usertoken=46ff078c-80ed-4fa3-8805-a383275e95af; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/Uf1ufiM5N/TQe2wIdQFoVIFlyfG6GaeMxqgDgrNRS06695S3zHV93wef3yV2JyrWzwafA7xuzMKk4gLie0/zsAcViXnXebazJy5XcPHUSzbniUbawMQe1GyhEciLJLi2J25h8qTXkY6ad37w7TmMX4pVKka13UsgL5p540vbw4hrjb55pJwyeeBunGkP32X+GN; logintype=1; _bfa=1.1710388272093.940b2eHguev6.1.1719807331768.1719807334093.12.155.10650082358"
        hotel:
          - name: "北門窩泊旅"
            hotelid: "6532235"
            hotelid_pre: "119853401"
            masterhotelid: "6083160"
            batchid: ""
            token: ""
          - name: "台北西門窩青年旅館"
            hotelid: ""
            hotelid_pre: "1594796" # 119853458
            masterhotelid: "1594815"
            batchid: ""
            token: ""
          - name: "府城窩旅"
            hotelid: "81309083"
            hotelid_pre: "119852951"
            masterhotelid: "79036502"
            batchid: ""
            token: ""
          - name: "洄瀾窩青年旅舍"
            hotelid: "119851634"
            hotelid_pre: "119851677"
            masterhotelid: "2592721"
            batchid: ""
            token: ""
          - name: "三德大飯店"
            hotelid: ""
            hotelid_pre: "6283696" # 119853427 #特例:現付帳號但要在預付中查看訂單
            masterhotelid: "701791"
            batchid: ""
            token: ""
          - name: "安蘭居旅店"
            hotelid: "3120533"
            hotelid_pre: "3525613"
            masterhotelid: "986103"
            batchid: ""
            token: ""
          - name: "福憩背包客棧和平館"
            hotelid: ""
            hotelid_pre: "2905496"
            masterhotelid: "2905493"
            batchid: ""
            token: ""
          - name: "福憩背包客棧緣憩館"
            hotelid: ""
            hotelid_pre: "2907751"
            masterhotelid: "2907741"
            batchid: ""
            token: ""
          - name: "幸福旅行.舍"
            hotelid: ""
            hotelid_pre: "1117056"
            masterhotelid: "1117126"
            batchid: ""
            token: ""
          - name: "欣京棧民宿"
            hotelid: ""
            hotelid_pre: "83327670"
            masterhotelid: "83277418"
            batchid: ""
            token: ""
          - name: "京棧興盛民宿"
            hotelid: ""
            hotelid_pre: "2381243"
            masterhotelid: "2381244"
            batchid: ""
            token: ""
          - name: "享棧民宿"
            hotelid: ""
            hotelid_pre: "50122578"
            masterhotelid: "19830620"
            batchid: ""
            token: ""
          - name: "月牙泉渡假行館"
            hotelid: "2704791"
            hotelid_pre: "971311"
            masterhotelid: "971336"
            batchid: ""
            token: ""
          - name: "松悅民宿"
            hotelid: ""
            hotelid_pre: "85030758"
            masterhotelid: "84944102"
            batchid: ""
            token: ""
          - name: "Amber Cove"
            hotelid: ""
            hotelid_pre: "112491414"
            masterhotelid: "112490477"
            batchid: ""
            token: ""
          - name: "亞馨文旅"
            hotelid: ""
            hotelid_pre: "1334234"
            masterhotelid: "1233126"
            batchid: ""
            token: ""
          - name: "Lucentia Residence BBCC Lalaport at Kuala Lumpur By Luxe Home	"
            hotelid: ""
            hotelid_pre: "113587355"
            masterhotelid: "113577881"
            batchid: ""
            token: ""
          - name: "Sentral Suite By Luxe Home"
            hotelid: ""
            hotelid_pre: "114057828"
            masterhotelid: "114047005"
            batchid: ""
            token: ""
          - name: "Tropicana Residence By Luxe Home"
            hotelid: ""
            hotelid_pre: "117614530"
            masterhotelid: "117491538"
            batchid: ""
            token: ""
          - name: "D'Majestic By Luxe Home"
            hotelid: ""
            hotelid_pre: "114679389"
            masterhotelid: "114673603"
            batchid: ""
            token: ""
          - name: "九份山嶼海民宿"
            hotelid: "18041557"
            hotelid_pre: "18041559"
            masterhotelid: "18041556"
            batchid: ""
            token: ""
          - name: "逢甲二五行館"
            hotelid: "114242053"
            hotelid_pre: "114242056"
            masterhotelid: "19831065"
            batchid: ""
            token: ""
          - name: "台中传思文旅"
            hotelid: "6484937"
            hotelid_pre: "6484938"
            masterhotelid: "6484936"
            batchid: ""
            token: ""

  - name: "敦謙"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; OrderCount=9; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1719802347&Expires=1720407146757; imislogin=9597315^1; librauuid=; randomkey=d5e8b572-aac4-4eaa-a545-a8858a3319e1; usertoken=d5e8b572-aac4-4eaa-a545-a8858a3319e1; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/UfE8U6W7PqTtOWkZlU8GcNPGD8prM8y3IsjLSD+70+uPpZ66OrKooGrJIsroqTvjnpM1sQO4dBfk2AQfmWtRzCQFp7+Ng6EV//i/I9rtk/XiTTZ0GFkY8mihLCItw0EA7t4cMYDSCME4U9VurRmCcEFTSvwPJbso6mlQJ/26WsoJEMFHUu20DKmFJxIw0+1MxQ; logintype=1; _bfa=1.1710388272093.940b2eHguev6.1.1719806375596.1719806376245.12.103.10650082376"
        hotel:
          - name: "	CHECK inn Phnom Penh BKK1"
            hotelid: ""
            hotelid_pre: "104578764"
            masterhotelid: "103678440"
            batchid: ""
            token: ""
          - name: "	CHECK inn Phnom Penh Royal Palace"
            hotelid: ""
            hotelid_pre: "109885741"
            masterhotelid: "107844200"
            batchid: ""
            token: ""
          - name: "漢彌敦大飯店"
            hotelid: "118890069"
            hotelid_pre: ""
            masterhotelid: "1232333"
            batchid: "9357669"
            token: "47727526E3F3319B0AC6517B4ABF344B"
          - name: "夢樓旅店"
            hotelid: "16159276"
            hotelid_pre: ""
            masterhotelid: "16159275"
            batchid: "9367479"
            token: "598C3F3F0D406C075CB47B5EFD68A13D"
          - name: "承攜行旅台北大稻埕館"
            hotelid: "5915987"
            hotelid_pre: ""
            masterhotelid: "2346507"
            batchid: "9377097"
            token: "3AB3BE88295ED83724E7D0022DE81BC1"
          - name: "給恰旅店"
            hotelid: "52179858"
            hotelid_pre: ""
            masterhotelid: "41900364"
            batchid: ""
            token: ""

  # - name: "上海雀の花园民宿"
  #   platform:
  #     - name: "Ctrip"
  #       cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; OrderCount=6; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1714532684&Expires=1715137483893; imislogin=9917687^1; librauuid=; randomkey=c89702a8-193f-44c3-ba16-be98ee25f43b; usertoken=c89702a8-193f-44c3-ba16-be98ee25f43b; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/UfF/nvaRPtGW+JymuzxUqBH6gemUFmgleoaJGdCZP9uvD8T1diZSCPvV/3ZBecha/dXzelNafnSIRZjPmCtaWiJiyeyhhooQ6agLYnuRHODM/i6A7oNgAfVKh0S+uzVTzJtBF+ftGy1nTIHG2t+rFxf1A+GpGK9fmkV7MkzVcWRsYgmVZvCz0yqpyUguIdgGnj; logintype=1; hotelhst=1164390341; userRoleNew_8871149=director; _bfa=1.1710388272093.940b2eHguev6.1.1714533848531.1714533852807.8.86.10650061100"
  #       hotel:
  #         - name: "上海雀の花园民宿"
  #           hotelid: ""
  #           hotelid_pre: "64979985"
  #           masterhotelid: ""
  #           batchid: ""
  #           token: ""

  # - name: "豐豐民宿"
  #   platform:
  #     - name: "Ctrip"
  #       cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1714532684&Expires=1715137483893; imislogin=9917687^1; librauuid=; hotelhst=1164390341; userRoleNew_8871149=director; OrderCount=4; randomkey=4fff78f7-2f94-4dd2-a39d-fe2af5c065c6; usertoken=4fff78f7-2f94-4dd2-a39d-fe2af5c065c6; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/Uf8QFq0f8rJdNCJlyhy7SW0rxPo7fPWLNKDZnuf4vXXUtEPATnRClOi/gAmKTfZR1/EBQERJQzFRAS5Mn1QwSbHXULbBsefENvzchb1xD4mRJ3tjSPK/QBhBKGcbwTgNoy/QfomhCJNqiDOc2aRuR8pERpd538wYUGGMkT3N6c3i3Zbw4SnkRkh4DOULvgpRnm; logintype=1; userRoleNew_10139731=director; _bfa=1.1710388272093.940b2eHguev6.1.1714533907818.1714533911768.8.92.10650061100"
  #       hotel:
  #         - name: "豐豐民宿"
  #           hotelid: ""
  #           hotelid_pre: "117959504"
  #           masterhotelid: ""
  #           batchid: ""
  #           token: ""
