period: "2024-04"
account:
  - name: "mrhost"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; OrderCount=6; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1714532684&Expires=1715137483893; imislogin=9917687^1; librauuid=; randomkey=55a134c0-7a2f-4738-a2cb-8fb7a47bf177; usertoken=55a134c0-7a2f-4738-a2cb-8fb7a47bf177; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/Uf1ufiM5N/TQe2wIdQFoVIFoMwb9bbrgr6GJ0VMUuVxv4WhDC5/butQx0h2dKwThfMafA7xuzMKk4gLie0/zsAcViXnXebazJy5XcPHUSzbnhcK1HpdHGO4donFhYYC6ctpRD4tEzHqzVkv5MsFdjxkpIHZaNNQ0lQp7NStRuBqGbJspPl9uDswJLNHWRDxMi6; logintype=1; _bfa=1.1710388272093.940b2eHguev6.1.1714533155722.1714533158159.8.47.10650101018"
        hotel:
          - name: "北門窩泊旅"
            hotelid: "6532235"
            hotelid_pre: "6532236"
            masterhotelid: "6083160"
            batchid: ""
            token: ""
          - name: "台北西門窩青年旅館"
            hotelid: "4046846"
            hotelid_pre: "1594796"
            masterhotelid: "1594815"
            batchid: ""
            token: ""
          - name: "府城窩旅"
            hotelid: "81309083"
            hotelid_pre: "81309084"
            masterhotelid: "79036502"
            batchid: ""
            token: ""
          - name: "洄瀾窩青年旅舍"
            hotelid: "5338513"
            hotelid_pre: "2592723"
            masterhotelid: "6083160"
            batchid: "9251151"
            token: "F6658F26E24E1D8A4AEED0D24D51AC2F"
          - name: "三德大飯店"
            hotelid: ""
            hotelid_pre: "6283696" #特例:現付帳號但要在預付中查看訂單
            masterhotelid: "701791"
            batchid: ""
            token: ""
          - name: "安蘭居旅店"
            hotelid: "3120533"
            hotelid_pre: "3525613"
            masterhotelid: "986103"
            batchid: ""
            token: ""
          - name: "福憩背包客棧和平館"
            hotelid: ""
            hotelid_pre: "2905496"
            masterhotelid: "2905493"
            batchid: ""
            token: ""
          - name: "福憩背包客棧緣憩館"
            hotelid: ""
            hotelid_pre: "2907751"
            masterhotelid: "2907741"
            batchid: ""
            token: ""
          - name: "幸福旅行.舍"
            hotelid: ""
            hotelid_pre: "1117056"
            masterhotelid: "1117126"
            batchid: ""
            token: ""
          - name: "欣京棧民宿"
            hotelid: ""
            hotelid_pre: "83327670"
            masterhotelid: "83277418"
            batchid: ""
            token: ""
          - name: "京棧興盛民宿"
            hotelid: ""
            hotelid_pre: "2381243"
            masterhotelid: "2381244"
            batchid: ""
            token: ""
          - name: "享棧民宿"
            hotelid: ""
            hotelid_pre: "50122578"
            masterhotelid: "19830620"
            batchid: ""
            token: ""
          - name: "月牙泉渡假行館"
            hotelid: "2704791"
            hotelid_pre: "971311"
            masterhotelid: "971336"
            batchid: ""
            token: ""
          - name: "松悅民宿"
            hotelid: ""
            hotelid_pre: "85030758"
            masterhotelid: "84944102"
            batchid: ""
            token: ""
          - name: "Amber Cove"
            hotelid: ""
            hotelid_pre: "112491414"
            masterhotelid: "112490477"
            batchid: ""
            token: ""
          - name: "亞馨文旅"
            hotelid: ""
            hotelid_pre: "1334234"
            masterhotelid: "1233126"
            batchid: ""
            token: ""
          - name: "Lucentia Residence BBCC Lalaport at Kuala Lumpur By Luxe Home	"
            hotelid: ""
            hotelid_pre: "113587355"
            masterhotelid: "113577881"
            batchid: ""
            token: ""
          - name: "Sentral Suite By Luxe Home"
            hotelid: ""
            hotelid_pre: "114057828"
            masterhotelid: "114047005"
            batchid: ""
            token: ""
          - name: "Tropicana Residence By Luxe Home"
            hotelid: ""
            hotelid_pre: "117614530"
            masterhotelid: "117491538"
            batchid: ""
            token: ""
          - name: "D'Majestic By Luxe Home"
            hotelid: ""
            hotelid_pre: "114679389"
            masterhotelid: "114673603"
            batchid: ""
            token: ""
          - name: "九份山嶼海民宿"
            hotelid: "18041557"
            hotelid_pre: "18041559"
            masterhotelid: "18041556"
            batchid: ""
            token: ""

  - name: "敦謙"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; OrderCount=6; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; randomkey=359a0d39-7370-4fea-b451-e5a0e07973d0; usertoken=359a0d39-7370-4fea-b451-e5a0e07973d0; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/UfE8U6W7PqTtOWkZlU8GcNPKNYtC9gwHfWcYSb1t5skw2xQx7yG3kt9igspwR2Bx0sM1sQO4dBfk2AQfmWtRzCQFp7+Ng6EV//i/I9rtk/XiRto/O7z66ubu4vkEL9W3tk3m4Rnb+jdYri7RP033SWvqLR7Ec2Sk1JjfRr8oJc/yAERds358mtQ+bQ29hPTHHT; logintype=1; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1714532684&Expires=1715137483893; imislogin=9917687^1; librauuid=; _bfa=1.1710388272093.940b2eHguev6.1.1714533022021.1714533025404.8.40.10650101018"
        hotel:
          - name: "	CHECK inn Phnom Penh BKK1"
            hotelid: ""
            hotelid_pre: "104578764"
            masterhotelid: "103678440"
            batchid: ""
            token: ""
          - name: "	CHECK inn Phnom Penh Royal Palace"
            hotelid: ""
            hotelid_pre: "109885741"
            masterhotelid: "107844200"
            batchid: ""
            token: ""
          - name: "漢彌敦大飯店"
            hotelid: "6106050"
            hotelid_pre: ""
            masterhotelid: "1232333"
            batchid: "9290414"
            token: "E08231009A6CE18AE1F9132E2603C770"
          - name: "夢樓旅店"
            hotelid: "16159276"
            hotelid_pre: ""
            masterhotelid: "16159275"
            batchid: "9258868"
            token: "B5A171EF3EA656109E2E9B5630D441A9"
          - name: "承攜行旅台北大稻埕館"
            hotelid: "5915987"
            hotelid_pre: ""
            masterhotelid: "2346507"
            batchid: "9245469"
            token: "0E596554B33BF682A5DCF007859921A5"
          - name: "給恰旅店"
            hotelid: "52179858"
            hotelid_pre: ""
            masterhotelid: "41900364"
            batchid: "9245862"
            token: "5715DC96370BDF35C1126BB81C2500EA"

  - name: "上海雀の花园民宿"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; OrderCount=6; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1714532684&Expires=1715137483893; imislogin=9917687^1; librauuid=; randomkey=c89702a8-193f-44c3-ba16-be98ee25f43b; usertoken=c89702a8-193f-44c3-ba16-be98ee25f43b; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/UfF/nvaRPtGW+JymuzxUqBH6gemUFmgleoaJGdCZP9uvD8T1diZSCPvV/3ZBecha/dXzelNafnSIRZjPmCtaWiJiyeyhhooQ6agLYnuRHODM/i6A7oNgAfVKh0S+uzVTzJtBF+ftGy1nTIHG2t+rFxf1A+GpGK9fmkV7MkzVcWRsYgmVZvCz0yqpyUguIdgGnj; logintype=1; hotelhst=1164390341; userRoleNew_8871149=director; _bfa=1.1710388272093.940b2eHguev6.1.1714533848531.1714533852807.8.86.10650061100"
        hotel:
          - name: "上海雀の花园民宿"
            hotelid: ""
            hotelid_pre: "64979985"
            masterhotelid: ""
            batchid: ""
            token: ""

  - name: "豐豐民宿"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Union=AllianceID=4899&SID=135371&OUID=&createtime=1714532684&Expires=1715137483893; imislogin=9917687^1; librauuid=; hotelhst=1164390341; userRoleNew_8871149=director; OrderCount=4; randomkey=4fff78f7-2f94-4dd2-a39d-fe2af5c065c6; usertoken=4fff78f7-2f94-4dd2-a39d-fe2af5c065c6; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/Uf8QFq0f8rJdNCJlyhy7SW0rxPo7fPWLNKDZnuf4vXXUtEPATnRClOi/gAmKTfZR1/EBQERJQzFRAS5Mn1QwSbHXULbBsefENvzchb1xD4mRJ3tjSPK/QBhBKGcbwTgNoy/QfomhCJNqiDOc2aRuR8pERpd538wYUGGMkT3N6c3i3Zbw4SnkRkh4DOULvgpRnm; logintype=1; userRoleNew_10139731=director; _bfa=1.1710388272093.940b2eHguev6.1.1714533907818.1714533911768.8.92.10650061100"
        hotel:
          - name: "豐豐民宿"
            hotelid: ""
            hotelid_pre: "117959504"
            masterhotelid: ""
            batchid: ""
            token: ""
