period: "2024-06"
account:
  - name: "mrhost"
    platform:
      - name: "MastriPMS"
        hotel:
          - name: "guidetpedadaocheng"
          - name: "getchahostel"
          - name: "hamiltonhotel"
          - name: "dreammansionhotel"
