period: "2024-03"
account:
  # - name: "mrhost"
  #   platform:
  #     - name: "Ctrip"
  #       cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; logintype=1; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Session=smartlinkcode=U59318281&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; randomkey=8b38409c-985f-474d-be73-0ec6e58eac74; usertoken=8b38409c-985f-474d-be73-0ec6e58eac74; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/Uf1ufiM5N/TQe2wIdQFoVIFksWP84EADbYzwmMvWKHd13hrnl0N2lbRXbRP+yKBhKLafA7xuzMKk4gLie0/zsAcViXnXebazJy5XcPHUSzbnjymy6CHmIgCuxIeaA26zcdcOoYGE/biLuQ5etPy0bQAWK43pwGMVTUEcX/JWmYMzGebTt0A58qMoZFcTB3W2xl; imislogin=9597315^1; librauuid=; Union=AllianceID=66672&SID=59318281&OUID=&createtime=1711953543&Expires=1712558342651; _bfa=1.1710388272093.940b2eHguev6.1.1711953547942.1711953551408.3.17.10650082358"
  #       hotel:
  #         - name: "北門窩泊旅"
  #           hotelid: "6532235"
  #           hotelid_pre: "6532236"
  #           masterhotelid: "6083160"
  #           batchid: ""
  #           token: ""
  #         - name: "台北西門窩青年旅館"
  #           hotelid: "4046846"
  #           hotelid_pre: "1594796"
  #           masterhotelid: "1594815"
  #           batchid: ""
  #           token: ""
  #         - name: "府城窩旅"
  #           hotelid: "81309083"
  #           hotelid_pre: "81309084"
  #           masterhotelid: "79036502"
  #           batchid: ""
  #           token: ""
  #         - name: "洄瀾窩青年旅舍"
  #           hotelid: "5338513"
  #           hotelid_pre: "2592723"
  #           masterhotelid: "6083160"
  #           batchid: "9190640"
  #           token: "9F5C23CD0148A9088C6B835B9AAD62B0"
  #         - name: "三德大飯店"
  #           hotelid: ""
  #           hotelid_pre: "6283696" #特例:現付帳號但要在預付中查看訂單
  #           masterhotelid: "701791"
  #           batchid: ""
  #           token: ""
  #         - name: "安蘭居旅店"
  #           hotelid: "3120533"
  #           hotelid_pre: "3525613"
  #           masterhotelid: "986103"
  #           batchid: ""
  #           token: ""
  #         - name: "福憩背包客棧和平館"
  #           hotelid: ""
  #           hotelid_pre: "2905496"
  #           masterhotelid: "2905493"
  #           batchid: ""
  #           token: ""
  #         - name: "福憩背包客棧緣憩館"
  #           hotelid: ""
  #           hotelid_pre: "2907751"
  #           masterhotelid: "2907741"
  #           batchid: ""
  #           token: ""
  #         - name: "幸福旅行.舍"
  #           hotelid: ""
  #           hotelid_pre: "1117056"
  #           masterhotelid: "1117126"
  #           batchid: ""
  #           token: ""
  #         - name: "欣京棧民宿"
  #           hotelid: ""
  #           hotelid_pre: "83327670"
  #           masterhotelid: "83277418"
  #           batchid: ""
  #           token: ""
  #         - name: "京棧興盛民宿"
  #           hotelid: ""
  #           hotelid_pre: "2381243"
  #           masterhotelid: "2381244"
  #           batchid: ""
  #           token: ""
  #         - name: "享棧民宿"
  #           hotelid: ""
  #           hotelid_pre: "50122578"
  #           masterhotelid: "19830620"
  #           batchid: ""
  #           token: ""
  #         - name: "月牙泉渡假行館"
  #           hotelid: "2704791"
  #           hotelid_pre: "971311"
  #           masterhotelid: "971336"
  #           batchid: ""
  #           token: ""
  #         - name: "松悅民宿"
  #           hotelid: ""
  #           hotelid_pre: "85030758"
  #           masterhotelid: "84944102"
  #           batchid: ""
  #           token: ""
  #         - name: "Amber Cove"
  #           hotelid: ""
  #           hotelid_pre: "112491414"
  #           masterhotelid: "112490477"
  #           batchid: ""
  #           token: ""
  #         - name: "亞馨文旅"
  #           hotelid: ""
  #           hotelid_pre: "1334234"
  #           masterhotelid: "1233126"
  #           batchid: ""
  #           token: ""

  # - name: "敦謙"
  #   platform:
  #     - name: "Ctrip"
  #       cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Session=smartlinkcode=U59318281&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; imislogin=9597315^1; librauuid=; randomkey=e1510ccc-64db-491a-9ffb-1f1ca4b72cfc; usertoken=e1510ccc-64db-491a-9ffb-1f1ca4b72cfc; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/UfE8U6W7PqTtOWkZlU8GcNPHO2J4+8ucg7Dg8BHGrm01rN0iJfzpp7KWzZ88QI7xXjM1sQO4dBfk2AQfmWtRzCQFp7+Ng6EV//i/I9rtk/XiRbpJuRyW1PNkECFGzMLT/P4CON+7PwuMJqc84MfDD67OFzXTtcqGBShzjh43bX/QEBrASOW6Xq2nj9QYt+W2wB; logintype=1; Union=AllianceID=66672&SID=59318281&OUID=&createtime=1711954424&Expires=1712559224248; _bfa=1.1710388272093.940b2eHguev6.1.1711954425108.1711954425306.3.71.10650082358"
  #       fxpcqlniredt: "09031111118208455165"
  #       hotel:
  #         - name: "漢彌敦大飯店"
  #           hotelid: "6106050"
  #           hotelid_pre: ""
  #           masterhotelid: "1232333"
  #           batchid: "9194162"
  #           token: "69C2C063CE0348967EA3CC46BAD5C384"
  #         - name: "夢樓旅店"
  #           hotelid: "16159276"
  #           hotelid_pre: ""
  #           masterhotelid: "16159275"
  #           batchid: "9194869"
  #           token: "C9B3D450C2BF1CF40A93045680F20294"
  #         - name: "承攜行旅台北大稻埕館"
  #           hotelid: "5915987"
  #           hotelid_pre: ""
  #           masterhotelid: "2346507"
  #           batchid: "9200634"
  #           token: "2D5A3130DCBAAFCD9F12F4AAC057BC61"
  #         - name: "給恰旅店"
  #           hotelid: "52179858"
  #           hotelid_pre: ""
  #           masterhotelid: "41900364"
  #           batchid: "9190843"
  #           token: "BFC0DBD4067F47CE9740F94C50F64E32"

  # - name: "EBK"
  #   platform:
  #     - name: "Ctrip"
  #       cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Session=smartlinkcode=U59318281&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; imislogin=9597315^1; librauuid=; randomkey=68884dcb-aa6b-4715-94bc-2f15a35d64ed; usertoken=68884dcb-aa6b-4715-94bc-2f15a35d64ed; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/UfF/nvaRPtGW+JymuzxUqBH10F9zuR3lZ+0ETt+wDIEviR0PHRn1QDjWyQ0AzPsTehXzelNafnSIRZjPmCtaWiJiyeyhhooQ6agLYnuRHODM+kXMQL/sZ1pTLurFjZYNW5NJfeWXLuqtF+4+lYpVKznOU6Ai3tqzYSo1+fsaQeaA7uGCd+kKs2HWc40Fs9CpgT; logintype=1; Union=AllianceID=66672&SID=59318281&OUID=&createtime=1711954569&Expires=1712559368993; hotelhst=1164390341; _bfa=1.1710388272093.940b2eHguev6.1.1711954570421.1711954588287.3.77.10650061100; OrderCount=6"
  #       hotel:
  #         - name: "上海雀の花园民宿"
  #           hotelid: ""
  #           hotelid_pre: "64979985"
  #           masterhotelid: ""
  #           batchid: ""
  #           token: ""

  - name: "Other"
    platform:
      - name: "Ctrip"
        cookie: "EBK_CurrentLocale=zh-TW; CurrentLanguage=TraditionalChineseTW; GUID=09031043311840621561; UBT_VID=1710388272093.940b2eHguev6; _RF1=124.9.5.130; _RSG=v1KlZ8TFXq0bU9zVprNjX9; _RDG=2862618807d7782a5c0811bfebc6135982; _RGUID=0d213dd2-23bd-4079-986d-5f5cdff497a5; Session=smartlinkcode=U135371&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; Session=smartlinkcode=U59318281&smartlinklanguage=zh&SmartLinkKeyWord=&SmartLinkQuary=&SmartLinkHost=; imislogin=9597315^1; librauuid=; OrderCount=6; ibulanguage=CN; ibulocale=zh_cn; cookiePricesDisplayed=CNY; hotelhst=1164390341; randomkey=4ceec198-81e9-4dc8-9dae-85babd889b99; usertoken=4ceec198-81e9-4dc8-9dae-85babd889b99; usersign=ebk_token_rZqQSl8VNPFPvrHY8tM2RiiEObZXF5S4JLwH/qOruj7vPfIuzjJb2+rtpqgqjJCGvOb0WDiksQAHIeGqcN4XPlJy/YZEp79csfCwYzo2H6ZH0L0m2clTCbEnDOlUx/Uf8QFq0f8rJdNCJlyhy7SW0qCoPwjTV1ZTszDtJgqC0lGPitI2f4otfRs+v9+ZWPeTEBQERJQzFRAS5Mn1QwSbHXULbBsefENvzchb1xD4mRLnr1Lr7IKsALbCs9p/VmFFggZ9IuLXLGGMA9/xnz9Afg1b3h42Cg1zPKf/kcUXpFv70YZuAMitV5BMvDYzFaF2; logintype=1; Union=AllianceID=66672&SID=59318281&OUID=&createtime=1711955803&Expires=1712560603036; _bfa=1.1710388272093.940b2eHguev6.1.1711955814526.1711955818793.3.122.10650061100"
        hotel:
          - name: "豐豐民宿"
            hotelid: ""
            hotelid_pre: "117959504"
            masterhotelid: ""
            batchid: ""
            token: ""
