period: "2024-04"
account:
  - name: "mrhost"
    platform:
      - name: "Expedia"
        cookie: "linfo=v.4,|0|0|255|1|0||||||||1028|0|0||0|0|0|-1|-1; cookie_prompt=enabled; MC1=GUID=fc5fa9441831401bb47aa1c34a4a764a; DUAID=fc5fa944-1831-401b-b47a-a1c34a4a764a; osano_consentmanager_uuid=8bcdf5c3-4a66-42a6-9dd2-baefbe33d5ba; osano_consentmanager=FeVsbplHVEaaKYKGAO2O4q0A-U1-pOjcSrvFmTMej9ON8zSvOfOn7YSdAzudCj1B7E6tXlC4drJZR5tNHMxeT1Np-dKV5rhMlwkFuN-mG2mpLVrXZC8AQiTMDp-yu0XbpDANl5qFgeLB8hgapOF2EGTg7wH-lRWf0-In9hSHunJkYZVWYEIq0Dxqcd9NJftzOCar_0lJs38hx3CapZ3fcl0rmxe-GniMGWKMmRmnUwmfB1MgMc_JXrKgMAuB1w2COj_Xv5eRfFOZePWqo4l1hnX52npKA6J5lnuUKQ==; _ga=GA1.2.1510971469.1711945434; QuantumMetricUserID=7d8e19beb2f27678c978be936533724b; VSUPID=|0|72531976|; mdid=eLSQHMfuhVKb2lQsc5c2vQi547-tVxY4r7tPaRE59bfRqEnKh9k0JCyhvNoFvg-8PYeYPdGtx3YCNHvnehy2IQ; DUAID=fc5fa944-1831-401b-b47a-a1c34a4a764a; MC1=GUID=fc5fa9441831401bb47aa1c34a4a764a; EPCSession=8d14439aa629452fbb07e0d92fb50a54; verify_url_banner=enabled; ak_bmsc=2AA3373C649285E063C4F8EF1FBCCCAB~000000000000000000000000000000~YAAQbX8auJgC88yOAQAAibYGMhcw9hvU8f7qoRyXtcIxACUs0b2olZHIobh3PnBvslxJYqELhQ/hvUMhE5XW9AyPAp03Ep7OOv0CbunGYA3wZiIetaStfNFFt9jtH1kdBnsz39IBM4CMjrukLpH5NwL2pMK1IXvY42i7d3YJcBJaG+Z/1z2U4GYQaW8pzZasmbyQZ+hH5Ub46Hf+AFW3OuUu/9i9er7fRpSjF9GOCbp5y1lJBaKv3NlPvOOZbG7AWNguYqqN5ZvXepvtvT6gO3i4Okh9aCS4sx7f3BhWQAxRDYXyUE1E1s8aUTF8TO+uTAYYYTo4eToHuXlTI1fePzfiNqcBZrmmgmJcIlnzGNxU8UUROrAhM/rw93d8CLRNJDExy62OPxO2zse3JUJ4XJ1Las1yFNU=; _gid=GA1.2.1859041780.1714531253; QuantumMetricSessionID=68f08c4f56e164abbd139c0e855ce125; user=v.8,0,EX01D890D882$84$14001000$EF$E9$2A$0A8$C0S48$C0S48$C0S4$21O001000$1E31!90$F4$F9$CD!2$82$D7$DF$9D!i02000; minfo=v.5,EX01B79A8F79$2Dw7$32$CD$3CK$24$FAdYk4$5E$85pYk0$5E$85uYk8$5E$85oYk4$5E$85mYk4$5E$85hYk6$5E$85uYk4$5E$85pYk0$5E$85gYk6$5E$85$60Yk$1D$5E$85iYk$1D$5E$85hYk$1D$5E$85LYk; accttype=v.2,3,1,EX015B7D5C7F$2Dw7$32$D0$3CL$24$F3pYk8$5E$85pYk5$5E$85mYk5$5E$85mYk0$5E$85LYk; _abck=BB087B9C6E7EECF6F2632B3EB573EC4E~0~YAAQbX8auPgg88yOAQAAA24HMgtinWder7RX/Ayagjss/xnZ/px047+PGbjzaF3/FiLS6MAlILpLv6ZzSqUsIrOH90Oq8EIoBGMS7H0JuPvHrCmvwtblrQvsRSRN8PsiIFbphO1VZc0n/0s43b/y0mAH0rY4u13F1IZwE9veDbtpdH4e1fzxZ8sF9Jh1xNIGcMeAtLRcj2ZwQ1UZ0tnwOizD3z1Cv/5z6KQh1AT4565pO764VMgy/0mTfMzNPSOV2KrlEdGxI+OPtXdW6nQvtUYmEXZEl1wuJtq8pIJCubUHhF1CW1cIH+lNpY2bMXPYFfD+H7l2jBHSoHpog9MjaVK1tZhYuIHUCCONe2A9SamBRPpsNB2tQpZwzWrlfineTgijAyDAyIBM5V0sjx44DA29VY1fO236I+VpjnYh+DG57nvgoU+k~-1~-1~-1; EG_SESSIONTOKEN=PiSw-qXh6cbbkpS50-_JIqYKJf4ZDJzQxOVv2St4c40:VA5OA09kpbtqMq6Tsd8TSLsDmNFqwdSfznue8WIVeUc_r2dSkZuXRHrI-QmtnnbqwGjJE5fLVWAImQdgDNWvWQ; _gat_EPCldtAnalyticshome=1; EPC.ALP.3617420=Y; _gat_EPCPortalEPCHomeAdaptiveLandingPage=1; bm_sz=EBC941213DC7F67F13BC36F812B3DE6C~YAAQbX8auMo088yOAQAArOcHMheEnJ4K036YSWT8+Rs2iEpQDESQbvZ40IJOp1OvQ3nfgPGP4Fg4ZuyzHQEnLRiANbq1ay2hFob2wNEYJg0H/erE0EVLgIlYThym23QzysOIn8X+t/uqYhtrFVqq08vA5ni6YmEedI704CxvJXkq9UUMy/cCglArGizxOaUOyjsCMzZR5+UjGQ7W3mazI8XFaCyXruN/azPqPvkdRxVvKjmaI5XeWW6KRMzUTaGFoF0QErhoEYPipZYDSLyUq0BVcm6sxsvN6BzAPapznGXc58TMGvuhVnmGbppBAVJKtmX0chl1oIh//rrtlx5E9juK0pDR7MXPsNAMipGELPIWFVRKqiryHvzh4UocWBrnG5S8v2/3njfPIxNVulwiMzCVlGxZTIsDamBaUiXdmxPivXKQlGhAVNc3o+U+QxSQmKuI8pjDnLNaJp4=~3486260~4536119; _gat_EPCEPCReservationsFinanceReservationsSearchControllerloadReservationSearchPage=1; epcsid=eyJraWQiOiJlc3MtZGlyMSIsImFsZyI6ImRpciIsImVuYyI6IkExMjhDQkMtSFMyNTYifQ..nThxe-w3CVkrHwRJgp9isQ.rBTMQb28dYaHYlrSkMyEbfYZfLIzg4iMOA6WzI3dKLdLkhkKbxG-jYX_HS8Q1rXztHe21yBN6pAiultT27u91k0fjBmWh72_ucdS6KGOSKjWq4aAlJs-Q7c5Q829YJx4iCPTXV92x4LfSXymKVRnO-IEvRPkOpjil7NCsI5rvi-KMN-TgVT6XQ_xHcfkKJvqvQx-CgBQE3dJJmWjlM2aehZj4u2G1k1_8rRSva99WSW-kCcwHRUvn9NwytTSFNNGKdof7yuszKxQ5SZQyrKtDw.NSLpFotXyA7ewdp0VuB2Ug; bm_sv=CF43A4CE5FAFBB1079C03B516B8530B7~YAAQbX8auEU988yOAQAA+hkIMhd2wCvuEjUOceRs/cpNP4ZvfOoZNynLaFOm4+FpQrwe1oAVhBmASz3kbsnBBgWMheomBEvc/tOxzWz7v0GSQTDj9jcvVCDbmoSrhZL8y694bcdcUB/QiX3w3BMiUoK51Sjsr9yDKMuEK3jK/DyJAqKeLuvVTWOaFabD8cV4M+tCtZuKQ6GDMswa4kFO/2m/ELbXM4Iq6Fk8BQsR2Wtzlk2Wss9nN5PDxCd5zZ98V06fbv5tkgQwMtRQQl/juA==~1"
        hotel:
          - name: "北門窩泊旅"
            hotelid: "15811893"
          - name: "台北西門窩青年旅館"
            hotelid: "9557890"
          - name: "府城窩旅"
            hotelid: "92135130"
          - name: "洄瀾窩青年旅舍"
            hotelid: "11887295"
          - name: "三德大飯店"
            hotelid: "3617420"
          - name: "閑閑的海"
            hotelid: "37945905"
          - name: "安蘭居旅店"
            hotelid: "11848192"
          - name: "福憩背包客棧和平館"
            hotelid: "11598925"
          - name: "福憩背包客棧緣憩館"
            hotelid: "30029870"
          - name: "幸福旅行.舍"
            hotelid: "33006409"
          - name: "京棧興盛民宿"
            hotelid: "33744767"
          - name: "享棧民宿"
            hotelid: "17729727"
          - name: "CHECK inn Phnom Penh BKK1"
            hotelid: "39567468"
          - name: "CHECK inn Phnom Penh Royal Palace"
            hotelid: "49092341"
          - name: "月牙泉渡假行館"
            hotelid: "37209526"
          - name: "漢彌敦大飯店"
            hotelid: "33314830"
          - name: "夢樓旅店"
            hotelid: "19940738"
          - name: "承攜行旅台北大稻埕館"
            hotelid: "12224236"
          - name: "給恰旅店"
            hotelid: "31932838"
          - name: "清境31民宿"
            hotelid: "34886732"
          - name: 世良商務旅館"
            hotelid: "43098289"
          - name: "世良馨盈民宿"
            hotelid: "43101053"
          - name: "金洙椏民宿"
            hotelid: "9998041"
          - name: "尖尖民宿"
            hotelid: "36785692"
          - name: "亞馨文旅"
            hotelid: "5407951"
          - name: "九份山嶼海民宿"
            hotelid: "21481103"
