period: "2024-03"
account:
  - name: "mrhost"
    platform:
      - name: "Owlting"
        cookie: "__stripe_mid=7d23e151-7011-4e2a-9ad1-95805b207265799d7c; owlnest_admin_refresh_token=54d772bbe9f9ae568fc902aab11193631aee91e02daf55459ab4dee652fb914d; owlnest_admin_token=54d772bbe9f9ae568fc902aab11193635a9cebb8295aa9d4604602f046bd8b5e; lang=zh_TW; __stripe_sid=c602a162-7103-4a85-9d0a-f6ae29c4ca5a2e95a8; owlnest_admin_dialog={%22lastLogin%22:%222024-04-01%22%2C%22hotelId%22:5840%2C%22userId%22:8695%2C%22dialog%22:{}}; fcView=timelineSevenDays; owlnest_booking_engine_api_session=eyJpdiI6IlFhanBkQlNYeGtUWmFcL3MzbFdYamRBPT0iLCJ2YWx1ZSI6IndWdm1qd09IbEpWbzZja3BYQ3NkRWZDUGNKSjNFMXRNVk1NejNKMkZDcno5VFFwVlNXbHhteEFJVnZoMVVZVVFRXC9Ha1NLbjVZVlJIYmpsclE0cXFGWHlDT3g3RFFpeUFudG5HK2Uwb1wva1VqdWhQWW9OMFRvbFVveHFscFZFM3AiLCJtYWMiOiI0ZjZjNjY1NzI2ZjMwNWM1NDdmNThiZTZiZTJkMzNjNDdlOTEyOGRlZjBmNDRhZmI3NzAxZjRkNWE2MjE3NjA3In0%3D"
        hotel:
          - name: "安蘭居旅店"
            batchid: "3614"
          - name: "福憩背包客棧和平館"
            batchid: "791"
          - name: "福憩背包客棧緣憩館"
            batchid: "518"
          - name: "靜河畔民宿"
            batchid: "5840"
          - name: "清境31民宿"
            batchid: "4466"
          - name: "金洙椏民宿"
            batchid: "1866"
          - name: "菘畫居會館"
            batchid: "3160"
          - name: "阿爾卑斯莊園"
            batchid: "2618"
          - name: "海田行館"
            batchid: "1859"
